### ISSUE TITLE
"&" is causing error in android string resource xml

### ISSUE THREAD

**Issue by michaelhenry** [michaelhenry/Localizr#10]
escaping all the html related characters.

**Comment by michaelhenry** [comment]
e

**Comment by iyotetsuya** [comment]
@michaelhenry 
I still got the hint said `Unescaped & or nonterminated character/entity reference`
Did I miss anything to set?

**Comment by michaelhenry** [comment]
@iyotetsuya may i know what is the affected character? thank you

**Comment by iyotetsuya** [comment]
@michaelhenry the character `&` which be expected as `&amp;`.

**Comment by michaelhenry** [comment]
@iyotetsuya ah i see, i will check it. thanks

**Comment by michaelhenry** [comment]
@iyotetsuya I checked it and it actually converted to **&amps;**
here is the part of the response
```
<string name="terms_and_conditions">Terms &amp; Conditions</string>
```
