### ISSUE TITLE
Removing an user from Localizr, removes the keys added by that user.

### ISSUE THREAD

**Issue by diogopereira** [michaelhenry/Localizr#19]
Key added by a user should not be removed when removing that user.

**Comment by michaelhenry** [comment]
@diogopereira oh yes, that’s right. I Will create an update for that. Thanks

**Comment by michaelhenry** [comment]
@diogopereira I Just realized something, in the current model, if I remove the actual user from the database that means nullifiying the reference and will lose track the created or modified by information of some objects. I suggest to just remove the permissions of that user instead of deleting it which is already supported. Thank you. Unchecking staff can also use.

**Comment by diogopereira** [comment]
I think it still shouldn't remove the keys. It should either not remove them or provide the option to choose between having null references or removing the entries.

I bet that in 99% of the cases, you want to keep that user inputs.

**Comment by michaelhenry** [comment]
@diogopereira ok, I will remove the strict on_delete reference and nullify, BUT as I mentioned, if you delete it, it will make the `created` and `modified` to null. so it's up to the user which one is more important. Please check the latest tag once it's done.

**Comment by michaelhenry** [comment]
@diogopereira please check [v1.2.8](https://github.com/michaelhenry/Localizr/releases/tag/v1.2.8) in tag or in docker once done . and close this issue once confirmed. thank you.

**Comment by michaelhenry** [comment]
@diogopereira I have some change please use [v1.2.9](https://github.com/michaelhenry/Localizr/releases/tag/v1.2.9) instead or please wait for the dockerized image: [michaelhenry119/localizr:v1.2.9](https://hub.docker.com/r/michaelhenry119/localizr/tags/).

**Comment by michaelhenry** [comment]
Using the auto-deployed version in Heroku, I confirmed that this worked.

All objects related to Localizr are now not affected when deleting a user. So I will close this issue

![screen shot 2018-05-24 at 1 00 08 am](https://user-images.githubusercontent.com/717992/40436471-ff38fafa-5eed-11e8-8600-3ae4eceab547.png)

**Comment by michaelhenry** [comment]
![screen shot 2018-05-24 at 1 03 54 am](https://user-images.githubusercontent.com/717992/40436634-612d15f2-5eee-11e8-916f-5c0d8fb7994d.png)
