### ISSUE TITLE
Allow concurrent updates without overwriting values not edited

### ISSUE THREAD

**Issue by fmfer** [michaelhenry/Localizr#25]
When editing a String that has language A and B:

1) User A Open String(A,B) to edit language A
2) User B Open String(A,B) to edit language B
3) User A edits language A and stores String(A,B)
4) User B edits language B and stores String(A,B)

Result:

In Step 4 User B overwrites language A with the state how it was at step 2 when he first opened it.

This means, edits made by User A at step 3 get overwritten and lost.

Expected

Both edits are stored separately and without overwriting other language data.

Storing a modified string should only write the languages edited by the user, not the rest he didn't touch.

**Comment by michaelhenry** [comment]
@marcelof01 I will look into it. thanks

**Comment by fmfer** [comment]
Thanks! Great system btw! Hope you are doing great :D
