### ISSUE TITLE
Server Error (500) on export feature

### ISSUE THREAD

**Issue by iyotetsuya** [michaelhenry/Localizr#42]
I try to export a csv file for App's key but got Server Error (500).
Did I miss any setting for the project?

**Comment by michaelhenry** [comment]
@iyotetsuya thanks for this. I haven't used/check that feature for a long time.  I will check this thank you.

**Comment by michaelhenry** [comment]
@iyotetsuya it's now fixed. please wait for the changes after the CI. thanks

**Comment by michaelhenry** [comment]
https://travis-ci.org/michaelhenry/Localizr

**Comment by iyotetsuya** [comment]
thanks, it works now ~
