### ISSUE TITLE
Export published translations only?

### ISSUE THREAD

**Issue by dteoh** [michaelhenry/Localizr#47]
We made some translations with draft status but they still get exported, is it possible to export only the published ones?

**Comment by michaelhenry** [comment]
@dteoh yes it is supported. if you filter it **By status** and then export.

**Comment by dteoh** [comment]
Where in the UI do I go to do this?

I went to "App's Key -> Filter (select an app) -> Export" but there is no option for this.

I also tried `http://<host>/app/demo.ja?format=android&status=published` but that doesn't seem to work.

**Comment by michaelhenry** [comment]
@dteoh it’s under **LocalizedString**

-  http://host/Localizr/localizedstring/?status__exact=0

**Comment by michaelhenry** [comment]
@dteoh but for exporting to ios and android localization files, that one is not implemented yet, i just added it before just for only for tagging, but that one can be implemented easily.

**Comment by michaelhenry** [comment]
@dteoh please check https://github.com/michaelhenry/Localizr/releases/tag/v1.2.14

**Comment by dteoh** [comment]
Thanks, it works! 👍
