### ISSUE TITLE
Cannot pull latest release image

### ISSUE THREAD

**Issue by hsanson** [michaelhenry/Localizr#50]
Trying to pull the latest release docker image 1.2.14 results in an error. Seems the image is not available in the docker repo.

```
Pulling localizr (michaelhenry119/localizr:v1.2.14)...
ERROR: Get https://registry-1.docker.io/v2/michaelhenry119/localizr/manifests/v1.2.14: unauthorized: incorrect username or password
```

**Comment by michaelhenry** [comment]
@hsanson i have check the tags and it’s there https://hub.docker.com/r/michaelhenry119/localizr/tags/

Let me check it with my local machine

**Comment by michaelhenry** [comment]
@hsanson I was able to download it.

![Screen Shot 2019-04-01 at 14 32 00](https://user-images.githubusercontent.com/717992/55305372-17eb6180-548b-11e9-8339-ef2a06a37e41.png)

maybe there was an error with the registry?

Please check again. thanks

**Comment by hsanson** [comment]
Thanks, found the issue was due to an expired credential configured on our server. Removing the credential fixed the issue.

https://github.com/docker/hub-feedback/issues/1103#issuecomment-388103068
