### ISSUE TITLE
Can't create group or user with explizit permission

### ISSUE THREAD

**Issue by bobekos** [michaelhenry/Localizr#75]
Hi,

great tool. But i can't create a group or user with specific permissions. I got always a 500er Server Error

**Comment by michaelhenry** [comment]
hi @bobekos may I know what the log is? Thanks

Update:
I can't reproduce this on the demo app as well. I was able to create a group with a set of permission and assigned it to a user without a problem.

**Comment by bobekos** [comment]
Hi @michaelhenry 

we found the solution. It's because that the postgres version of the docker container is still on 9.4 in the [documentation](https://github.com/michaelhenry/Localizr#using-docker)

We have updated it to 9.5 and everything working fine now
